# Stage 1: Build the Vite app
FROM node:18 AS builder
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install --frozen-lockfile

# Copy the rest of the app files
COPY . .

# ENV
ENV VITE_REACT_APP_API_BASEURL=/api

# Build the Vite app
RUN npm run build

# Stage 2: Serve the app using NGINX
FROM nginx:alpine AS runner

# Copy the built files from the previous stage
COPY --from=builder /app/dist /usr/share/nginx/html

# Expose the port NGINX runs on
EXPOSE 80
