apiVersion: v1
kind: Service
metadata:
  name: mariadb-srv
spec:
  type: ClusterIP
  selector:
    app: maria-db
  ports:
  - port: 3306
    targetPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-nodeport
spec:
  type: NodePort
  selector:
    app: maria-db
  ports:
  - port: 3306
    targetPort: 3306
    nodePort: 30008
