apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-client
spec:
  replicas: 3
  selector:
    matchLabels:
      app: todo-client
  template:
    metadata:
      labels:
        app: todo-client
    spec:
      containers:
      - name: todo-client
        image: jigneng1/basic-k8s-todo-client:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5050
